### ISSUE TITLE
Document exported utils

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#146]

**Comment by rkillackey** [comment]
@dpikt Is this referring to adding `compareAtPath`, `objectify`, etc to the docs? It looks like they already have inline documentation

**Comment by dpikt** [comment]
Yep, since they're exported they should have fancy JSDocs

**Comment by rkillackey** [comment]
Gotcha, is any documentation needed for any of the other exported utils, i.e. from `lodash` or `lp-hoc`?

**Comment by dpikt** [comment]
Nope- and we shouldn't be exporting those 😀 
We should modify the main index to stop doing that!

**Comment by rkillackey** [comment]
@dpikt Forgot to check -- were you working on this one? If not, I've started and will take it

**Comment by dpikt** [comment]
@rkillackey nope, go ahead!

**Comment by dpikt** [comment]
@rkillackey nope, go ahead!

**Comment by dpikt** [comment]
@rkillackey nope, go ahead!
