### ISSUE TITLE
Handle `none` option in `CheckboxGroup`

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-components#170]
When `none` option is checked, it should uncheck all other options. When another option is checked while the `none` option is checked, it should uncheck the `none` option.

**Comment by dpikt** [comment]
@rkillackey Some additional questions about this enhancement:
- Do we want to disabled other options when "none" is selected?
- What is the value of the input when "none" is selected?
- Can there be multiple "none" options at once?
- Should we allow for an analogous "all" option?

**Comment by rkillackey** [comment]
@dpikt 
1. Maybe we can leave that up to the user, and have them pass in a prop like `disableOnNoneClick` or something
2. I think the user should be responsible for setting the "none" value through options.
3. Having trouble imagining this scenario. Was there one you had in mind?
4. Yes, but I think we should open a separate issue -- thoughts?

**Comment by dpikt** [comment]
@rkillackey makes sense to me! I think we should wait until another project needs this before porting it over from artlook- the logic is pretty idiomatic and I'm hoping it'll be limited to just that project (like all the table stuff).

**Comment by dpikt** [comment]
Closing this until it comes up on another project.
