### ISSUE TITLE
Add Spinner component

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#183]
Although I'm pretty sure it's just a div with id="spinner"

**Comment by rkillackey** [comment]
Yep, `<div id="spinner" />`

**Comment by dpikt** [comment]
We should also rename this to `Spinner` since the similarity to `LoadingContainer` has caused some confusion.

**Comment by rkillackey** [comment]
@dpikt  This is the css for the spinner div:

```
#spinner {
  @include rem(margin-top, 50px);
  text-align: center;

  &:after{
    border: 3px solid $blue-base;
    border-radius: 50%;
    border-top-color: $blue-base;
    border-right-color: transparent;
    border-top-color: transparent;
    content:"";
    display: inline-block;
    height: 30px;
    @include animation(spin 0.5s linear infinite);
    width: 30px;
  }
}

@include keyframes(spin) {
  to { @include transform(rotate(360deg)); }
}
```

Looks like it's using some Bourbon functionality. Should we try to refactor that out or include Bourbon in this library?

**Comment by dpikt** [comment]
@rkillackey I think we're already operating on the assumption that we're using bourbon and neat in all of our frontend projects.

**Comment by dpikt** [comment]
See https://github.com/LaunchPadLab/lp-components/blob/master/.storybook/webpack.config.js#L19

**Comment by rkillackey** [comment]
Ah, should've checked. Sounds good.
