### ISSUE TITLE
Pass `disabled` key to options in `Select`

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-components#195]
I have a use case for Empower Illinois where I need to add a few disabled options, which will act as headers for different sections within the dropdown. Currently we're only passing through the `key` and `value` keys in the `options` array. We could either pass through the `disabled` key or `..rest`.

**Comment by dpikt** [comment]
Makes sense to me! We should also consider whether we want to implement [optgroups](https://www.w3schools.com/tags/tag_optgroup.asp) in this component- not sure what the options array would look like in that case.

**Comment by rkillackey** [comment]
Oh good point! Using `optgroup` feels like a better idea to me.
