### ISSUE TITLE
Surrounding file input in `button` prevents file browser from opening in Firefox + IE

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-components#199]
Seems to be some type of security concern.

Instead of wrapping the `input` in a `Button` component, use a `div` instead. Spoke with Monique, and this will break some styles, but it's a pretty easy fix.

**Comment by dpikt** [comment]
Will this break any of the current component functionality? eg drag and drop?

**Comment by rkillackey** [comment]
Existing functionality appears to be in place, though I am testing with the updated component in Empower.
