### ISSUE TITLE
File type validation for file input

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#24]
Not sure how this would interact with validate.js, but it would be nice if we could pass an array of acceptable file types ( e.g. `['.png', '.jpg']`) to a `FileInput`.

**Comment by dpikt** [comment]
@rkillackey is this still a priority? I've been using the `accept` attribute and haven't yet run into a use case where it's been insufficient.

**Comment by rkillackey** [comment]
@dpikt Yep, agreed I think we can close this for now.

**Comment by dpikt** [comment]
🙌
