### ISSUE TITLE
Allow column-wide onClick on Table

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#257]
We can do this by adding it to the default table row component.

**Comment by dpikt** [comment]
Whoops, meant onClick.

**Comment by dpikt** [comment]
Ooh, actually that description doesn't make sense. It needs to be on the default table cell component. Sorry this issue is a trainwreck 😅

**Comment by rkillackey** [comment]
@dpikt Just checking -- the `onClick` should be for cells in a specific column? Not every table cell?

**Comment by dpikt** [comment]
@rkillackey yep!
