### ISSUE TITLE
Add filtering functionality to `SortableTable`

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-components#276]
Add filter option to table header, select from possible values, table data should be filtered (as opposed to just sorted) by selection.

UI example (from Empower): https://cl.ly/5f99130be671

cc @paulgonz6

**Comment by dpikt** [comment]
Can we accomplish this using the table-wide `onChange`?

**Comment by rkillackey** [comment]
Data-wise, yes we could. But we would also need to add the filtering indicator (in Status col of screenshot above) to the table headers.

**Comment by dpikt** [comment]
Ok cool, I'll open a ticket for that.
