### ISSUE TITLE
Button doesn't update classes correctly if `className` is provided

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#294]
If you pass `invalid={ true }`, you would expect the button to have class `is-disabled`, but it does not if you've already passed a `className` prop.

**Comment by chawes13** [comment]
Is this issue present for `submitting={ true }` and `in-progress`?

**Comment by chawes13** [comment]
@dpikt - Is it adding a disabled flag to the input? Instead of relying on adding a className can't you target the styles with a pseudo class?

https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled

**Comment by dpikt** [comment]
It's a problem with every computed class name, they get clobbered if `className` is passed instead of being added like you would expect. The styles relying on a class instead of the disabled flag is another issue :)

**Comment by chawes13** [comment]
Yeah, I actually ran into this issue this morning about 30 minutes after posting this. Upvote
