### ISSUE TITLE
Enable native date argument for DateInput `maxDate` 

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#300]
See https://github.com/LaunchPadLab/streamlined-checkout-client/pull/151/files

**Comment by chawes13** [comment]
There's also `minDate`, `excludeDates`, `highlightDates`, `highlightWithRanges`, `startDate`, and `endDate` that would be useful as well

**Comment by dpikt** [comment]
Should get resolved by #305

**Comment by dpikt** [comment]
Closed in favor of #305
