### ISSUE TITLE
Pass all Table props down to rowComponent 

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#307]

**Comment by mwislek** [comment]
Hey @dpikt ! 
When you say "all Table props" do you really mean "every single one"? I have a feeling you mean "a few". Here's the current list of table props:
```
function SortableTable({
  className,
  children,
  data: unsortedData,
  initialAscending,
  initialColumn,
  disableReverse,
  disableSort,
  controlled,
  onChange,
  rowComponent,
  headerComponent,
}) {
```

...and here's what's currently passed to the `rowComponent`:
```
function TableRow ({
  columns,
  rowComponent: RowComponent = DefaultRowComponent,
  rowData,
}) {
  return (
    <RowComponent { ...{ data: rowData } }>
```

I could see passing down `className`. I have another PR (https://github.com/LaunchPadLab/lp-components/pull/462) that allows one to pass arbitrary props to a table, all of which could also be passed to the `rowComponent`. Were you thinking of something else? Thanks!

**Comment by dpikt** [comment]
Hmm, honestly I don't remember the exact use case for this, I created it two years ago and didn't exactly clarify in the description 🤦 I think the idea was actually less about props and more about state (which were passed as props from a HOC at the time) which can be passed down manually when you define the component. That is, if you want a rowComponent that changes how it renders based on `sortPath`, right now it has no access to that information. So I think passing the internal table state as props to the row component (`ascending, sortPath, sortFunc, valueGetter`) would be adequate for this task.

**Comment by mwislek** [comment]
Thanks David! Your approach makes sense and will be implemented as such.

**Comment by chawes13** [comment]
Resolved by https://github.com/LaunchPadLab/lp-components/pull/464
