### ISSUE TITLE
HTML5 validation is overriding redux-form validation behavior

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#321]
https://cl.ly/6207bf525880

cc: @inveterateliterate

**Comment by chawes13** [comment]
Related to https://github.com/LaunchPadLab/lp-components/pull/310

**Comment by dpikt** [comment]
Would putting `novalidate` on the form resolve this?

**Comment by chawes13** [comment]
@dpikt using `noValidate` as a prop on the form does resolve this issue. Should I update the documentation to reflect this?

**Comment by dpikt** [comment]
That would be great! I also had a pipe dream a while ago of providing a pre-bound `Form` component prop from the `lpForm` HOC.... could be a method of resolution.

**Comment by dpikt** [comment]
(There are also a lot of reasons why that's a terrible idea.)
