### ISSUE TITLE
SortableTable swallows props

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#324]
Doesn't allow for passing things like `summary` or `aria-label`

**Comment by dpikt** [comment]
So extra props should be passed through to the `table` element?

**Comment by mwislek** [comment]
@chawes13 Was going to (finally) start working on this. I can easily pass any `...rest` props provided to `SortableTable` to the underlying `table` HTML. However, you mention `summary`. According to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table, `summary` is a deprecated attribute. If you want to use `summary` as a caption we can add a `caption` option to `SortableTable` though it might be better to simply arrange for your own caption outside of `SortableTable`.
