### ISSUE TITLE
Rows prop has no effect on Textarea

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#351]
Note: This might be related to the OOTB styes in the client template

**Comment by marchwiany** [comment]
@chawes13 I think I need a little more context, what are you trying to do?

**Comment by chawes13** [comment]
@marchwiany With this [height style applied](https://github.com/LaunchPadLab/client-template/blob/4d36762bb0263f95c18d52ca2bcd3eba752f762f/src/scss/components/_forms.scss#L113), the [rows](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-rows) attribute is ignored.

![Screen Recording 2021-09-21 at 08 29 15 AM](https://user-images.githubusercontent.com/20426095/134179515-49494ff3-07e5-4094-bbeb-e15a279c6bf5.gif).

The rows default for a textarea element is 2. Should we change that in our element to 4 (close to 100px)?

**Comment by chawes13** [comment]
@marchwiany Could you take a look at https://github.com/LaunchPadLab/lp-components/issues/351#issuecomment-923992333 when you get a chance?
