### ISSUE TITLE
Add props for directly accessing upload response

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#378]
Since `CloudinaryInput` is running the upload `onChange`, `redux-form` doesn't catch the exception that is thrown. It results in an unhandled rejected promise. How can we access / handle this error?

**Comment by dpikt** [comment]
Hmm. I don't think there's a way to directly pass this to redux form. But we could add props for accessing the info at the very least.

```jsx
 onLoad={ (fileData, file) => upload(fileData, file)
  .then(res => {
    onChange(res.url)
    return onUploadSuccess(res)
  }, err => onUploadFailure(err))
}
```
Callbacks defaulted to noops. Note the second argument to `.then` to avoid catching errors in `onUploadSuccess`, been burned too many times on that 😀

**Comment by chawes13** [comment]
@dpikt I actually haven't been burned by that before - good to know the distinction!

**Comment by dpikt** [comment]
I burn so others may remain unburned 🙏
