### ISSUE TITLE
File Input does not get reset after redux-form `reset()`

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#387]
The form value in the redux store gets cleared, but neither the internal component state (used for generating preview) or the input's value get cleared

**Comment by dpikt** [comment]
Can you bundle a fix for this into #346? Should be doable with a lifecycle hook. https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops perhaps?

**Comment by dpikt** [comment]
Not sure how this article factors in... 🤔 https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by chawes13** [comment]
@dpikt My takeaway from that is that we should store an array of files as the value for the input and get rid of internal state. Would that approach lend itself more naturally to a field array?
