### ISSUE TITLE
NavLink not recognizing wrapping ConnectedRouter 

### ISSUE THREAD

**Issue by aojin** [LaunchPadLab/lp-components#448]
NavLinks throw an error when used within ConnectedRouter. Probably tied to an outdated version of React Router.

**Comment by dpikt** [comment]
@aojin can you attach a screenshot or copied snippet of the error text?

**Comment by chawes13** [comment]
@aojin Is this still an issue?

**Comment by chawes13** [comment]
This is no longer relevant, since `<NavLink />` was removed in v6
