### ISSUE TITLE
Cannot programmatically focus the textarea input in the Textarea component

### ISSUE THREAD

**Issue by danparnella** [LaunchPadLab/lp-components#470]
Without using DOM traversal with standard Javascript, I haven't been able to find a way to programmatically focus the textarea input in the `Textarea` component. My suggestion is to allow for a `forwardRef` prop on `Textarea` that would be passed down to the textarea input. That ref could then be used to target the input itself for focusing.

**Comment by chawes13** [comment]
I ran into this issue yesterday with our base `Input` component.

Can we use [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html)? Here's a reference from Styled Components: https://github.com/system-ui/theme-ui/pull/817/files

Ideally this would be applied to all of our inputs, but I'm ok with that being a separate PR to expedite the fix for Artlook

**Comment by chawes13** [comment]
That being said, we will probably run into an issue with how `redux-form`s `Field` component wraps our components. From the [documentation](https://redux-form.com/8.3.0/docs/api/field.md/#-code-forwardref-boolean-code-optional-), it looks like their ref forwarding implementation via `getRenderedComponent` only works if the component is a class component.

I initially thought we might be able to get away with something like the below, but haven't tested it. I did see one SO post that said it wasn't working for them.
```jsx
<Field
  name="content"
  component={(props) => <Input ref={inputRef} {...props} />}
/>

**Comment by danparnella** [comment]
Yeah, that was originally was my hope (to just export our component with `forwardRef`), but yes I ran straight into that class restriction ☹️ . Your last suggestion is basically what I ended up doing in my band-aid override, but without the fallback to using the correct `forwardRef` implementation (and I think I could use `forwardRef` in my `Field` in artlook because we're using an older version of `redux-form`), so I think what you have is the way to go.

I plan on getting a PR up for this today!

**Comment by danparnella** [comment]
@chawes13 I'm running into some bumps in the road represented by [this issue](https://github.com/facebook/react/issues/16653). Does that make sense in that I need to define prop types and default props _after_ exporting `Textarea` as a `forwardRef`?

**Comment by chawes13** [comment]
@danparnella Did you try the solution outlined in this comment? https://github.com/facebook/react/issues/16653#issuecomment-564423981

**Comment by danparnella** [comment]
Got it, got it. Ok, just wanted to make sure I didn't go too off the rails with our patterns 👍 .

**Comment by chawes13** [comment]
Uncharted territory 🤪
