### ISSUE TITLE
Remove SetterLink component

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#524]
Instead of using this component, we should be pushing devs to use [semantic form elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#forms) (e.g., checkbox, radio group, or select).

Not only is this not a semantic element, it's also an inappropriate use of an anchor tag, since it's not used for navigation and is not in the tab order. Source: http://itstiredinhere.blogspot.com/2014/08/the-anchor-button-bad-for-accessibility.html.

**Comment by chawes13** [comment]
@bhennes2 @inveterateliterate @dianacamacho Are you aware of any projects currently using this component? I did a search and found it in mmrf and uolf. I recently had a conversation with Nikki about replacing it on uolf, so there may not be any other _active_ projects using it. Let me know if you have any concerns with removing it!

**Comment by inveterateliterate** [comment]
I have not seen this in the projects I have been active on!

**Comment by dianacamacho** [comment]
Outside of uolf, i dont think so!
