### ISSUE TITLE
Replace Enzyme with React Testing Library

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#567]
This will accommodate allowing this library to be confidently tested against React 18.

Enzyme does not officially support v18 (or v17 for that matter). The author of the unofficial v17 adapter has recommended switching to RTL and considers Enzyme "dead".

https://github.com/enzymejs/enzyme/issues/2524
https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl
https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/

**Comment by josiasds** [comment]
@chawes13 I assume we can close this issue now?

**Comment by chawes13** [comment]
😲 I guess we didn't use the right keywords to link this issue! Yes, definitely.
