### ISSUE TITLE
Button - style: small Crashing in Storybook

### ISSUE THREAD

**Issue by JoseWhite** [LaunchPadLab/lp-components#629]
## Environment

- `@launchpad/lp-components` version: 9.3.0
- `react` version: 6.4.22
- `node` version: ^18.12 || ^20.0

## Expected Behavior
Deployed storybook should display the Button - style: small correctly.

## Current Behavior
![image](https://github.com/LaunchPadLab/lp-components/assets/28409950/85b2d832-f538-4137-a81e-a2e05bcdde42)

## Steps to Reproduce
Navigate to the [deployed Storybook](https://lp-components.herokuapp.com/storybook/index.html?path=/story/button--style-small)

## Suggested Solution
Fix the underlying issue, likely lives in the component or the story file.

**Comment by chawes13** [comment]
That's a cheeky suggested solution 😆 . Anything more specific we could use?
